language: python

python:
    - 2.7
    - 3.4

before_install:
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.26-1.linux-64.sh
    - sudo sh lilypond-2.19.26-1.linux-64.sh --batch

install:

    - pip install --allow-external abjad --allow-unverified abjad -e git://github.com/Abjad/abjad.git#egg=abjad
    - pip install --allow-external ide --allow-unverified ide -e git://github.com/Abjad/ide.git#egg=ide
    - pip install --allow-external baca --allow-unverified baca -e git://github.com/trevorbaca/baca.git#egg=baca
    - pip install -e .

script:
    - ajv doctest ./khamr -x
    #- py.test -rf ./khamr -x
    - ./khamr/test/run_tests_with_timing.py

notifications:
    email: false